service: AuthenticationService

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}

functions:
  authenticate:
    handler: handler.authenticate

package:
  exclude: 
    - 'test/**'
    - 'coverage/**'
    - 'LICENSE'
    - 'README.md'
    - '.travis.yml'
    - 'docs/**'
