service: ${file(./config/service_name.yml):service}
provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'development'}
  environment:
    STAGE: ${self:provider.stage}
    SLS_DEBUG: "*"
    PROVIDER: 'aws'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"       
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:*:${file(./credentials.json):environments.${self:provider.stage}.provider.aws.account}:table/${file(./parameters.json):environments.${self:provider.stage}.userTable}/*" 
functions:
  authenticate:
    handler: handler.authenticate

package:
  exclude: 
    - 'test/**'
    - 'coverage/**'
    - 'LICENSE'
    - 'README.md'
    - '.travis.yml'
    - 'docs/**'
    - 'handler_azure.js'
    - 'proxyRequest-function.json'
    - 'config/**'
